"""Structured blocking error codes for manufacturing validation."""

from __future__ import annotations

from enum import Enum


class BlockingCode(str, Enum):
    """Deterministic error codes — manufacturing pipeline must fail safely."""

    DRAWING_FRAME_SELECTED_AS_PART = "DRAWING_FRAME_SELECTED_AS_PART"
    TITLE_BLOCK_GEOMETRY_IN_PART = "TITLE_BLOCK_GEOMETRY_IN_PART"
    BBOX_DIMENSION_MISMATCH = "BBOX_DIMENSION_MISMATCH"
    HOLE_DIAMETER_MISMATCH = "HOLE_DIAMETER_MISMATCH"
    OPEN_OUTER_CONTOUR = "OPEN_OUTER_CONTOUR"
    SELF_INTERSECTION = "SELF_INTERSECTION"
    UNRESOLVED_SCALE = "UNRESOLVED_SCALE"
    UNSUPPORTED_GEOMETRY = "UNSUPPORTED_GEOMETRY"
    AMBIGUOUS_MAIN_CONTOUR = "AMBIGUOUS_MAIN_CONTOUR"
    UNRESOLVED_CRITICAL_DIMENSION = "UNRESOLVED_CRITICAL_DIMENSION"
    MISSING_PART_NUMBER = "MISSING_PART_NUMBER"
    MISSING_MATERIAL = "MISSING_MATERIAL"
    MISSING_THICKNESS = "MISSING_THICKNESS"
    MISSING_CONTOUR = "MISSING_CONTOUR"
    MANUFACTURING_NOT_READY = "MANUFACTURING_NOT_READY"
    DXF_ROUNDTRIP_FAILED = "DXF_ROUNDTRIP_FAILED"
    HOLE_OUTSIDE_OUTER = "HOLE_OUTSIDE_OUTER"
    NESTING_BLOCKED = "NESTING_BLOCKED"
